on:
  push:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/tests.yml"
name: tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x, 1.26.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        shell: bash
        # Exclude confidential transfer tests from running 100 times
        run: go test $(go list ./... | grep -v zk-elgamal-proof) -race -count=100
      - name: Confidential Transfer Tests
        shell: bash
        run: |
          go test ./programs/zk-elgamal-proof/... -race -count=1
          # Repeatedly race-check 8 concurrent goroutines generating proofs.
          go test ./programs/zk-elgamal-proof/proofdata -race -run TestConcurrentProofGeneration -count=20
